language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 5.0.102
branches:
  only:
    - master
#    - develop
script:
  - dotnet build
  - dotnet test
# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: travis-net5-327200-f9b54408c86d.json
    project: travis-net5-327200
    version: service-jhon
    default: true
    on:
        all_branches: true
# [END travis_deploy]